const chapters=[
['Auftrag & Verhalten','Aufgaben, Verhalten und Befehlskette.'],['Dienstantritt','Einweisung, UAFL und Dienstbeginn.'],['Uniform & Geräte','Uniform, Ausrüstung und Geräteeinweisung.'],['Funk & Rufnamen','Funkdisziplin, DDS, WWWB und Rufnamen.'],['Funkcodes','10-Codes und Einsatzmeldungen.'],['Ortskunde','PLZ-Gruppen und Standortmeldungen.'],['Laptop & Systeme','MDT, Units, CAD und Gesetzbuch.'],['EFA','Fahrzeugabfragen richtig durchführen.'],['Streifendienst','Fahrzeugübernahme und Streifenarbeit.'],['Bürgerkontakt','Verkehrskontrollen und professioneller Kontakt.'],['Gesetze & Rechte','Grundlagen, Maßnahmen und Rechtebelehrung.'],['Akten & Beweise','Berichte, Quellen und Beweismittel.'],['Einsatzmittel','Waffenumgang und Einsatzmittel.'],['Training & Tests','Schießtraining, Sporttest und G20.'],['Ausbildungsweg','Stufen, Weiterbildung und Freigaben.'],['Checklisten','Persönliche Einweisung und Nachweise.'],['Leitstelle','Calls, Units und Einsatzplanung.'],['Waffen & Munition','Modellkunde und Ausgabevermerke.'],['Labor','Beweismittel und Laborprüfung.'],['Merkwörter','Abkürzungen und Lernhilfen.'],['Gebietskarte','Zuständigkeitsgebiete und Orientierung.'],['Gefahrenlehre','Gefahren erkennen, melden und bewerten.']];
const icons=['◆','✓','▣','◉','⌁','⌖','▰','▱','▤','♙','⚖','▧','◈','◎','▲','☑','◫','◇','⌬','≡','⌖','⚠'];
const nav=document.querySelector('#nav');
nav.innerHTML='<div class="nav-group">ÜBERSICHT</div>'+navBtn('dashboard','⌂','Dashboard')+'<div class="nav-group">AUSBILDUNG</div>'+chapters.map((c,i)=>navBtn('c'+i,icons[i],c[0])).join('')+'<div class="nav-group">PERSÖNLICH</div>'+navBtn('account','♙','Mein Account');
function navBtn(id,ico,label){return `<button class="nav-item" data-page="${id}"><span class="ico">${ico}</span><span>${label}</span></button>`}
const content=document.querySelector('#content'), title=document.querySelector('#pageTitle');
const chapterContent={
0:['Unsere Aufgaben','Das Alta Police Department schützt die öffentliche Sicherheit, hilft Bürgern und bearbeitet Straftaten sowie Verkehrsangelegenheiten.','RKE: Ruhig bleiben – klar kommunizieren – Entscheidungen erklären.'],
1:['Deine erste Einweisung','Melde dich beim zuständigen FTO, übernimm die freigegebene Uniform, prüfe deine Ausrüstung und richte Funk, Diensttelefon und Laptop unter Anleitung ein.','UAFL: Uniform – Ausrüstung – Funk – Laptop. Vor der Abfahrt folgt die Fahrzeugkontrolle.'],
3:['Funkgerät vorbereiten','Dienstkanal einstellen, Lautstärke und Sprechtaste prüfen, Funkcheck durchführen und Bestätigung abwarten.','DDS: Denken – Drücken – Sprechen. WWWB: Wer – Wo – Was – Bedarf.'],
6:['Laptop und Dienstsysteme','Lerne Einsätze, Personen, Fahrzeuge, Fahndungen und Akten kennen. Im Desktop sind CAD, Units, Mitarbeiter und Gesetzbuch zentrale Anwendungen.','Der Fahrer bedient den Laptop nur bei sicher stehendem Fahrzeug.'],
8:['Fahrzeugübernahme','Fahrzeugklasse, sichtbare Schäden, Tankzustand und Ausstattung prüfen. Funk, Laptop und Rufnamen vorbereiten.','BBEHD: Beobachten – bewerten – entscheiden – handeln – dokumentieren.'],
9:['Professioneller Erstkontakt','Stelle dich vor, erkläre den Anlass, höre zu und erläutere die nächsten Schritte.','BKFA: Beobachtung – Kontakt – Feststellung – Abschluss.'],
10:['Gesetze anwenden','Jede Maßnahme muss auf eine passende Grundlage gestützt und nachvollziehbar dokumentiert werden.','GMD: Grundlage prüfen – Maßnahme begründen – dokumentieren.'],
14:['Dein Ausbildungsweg','Grundeinweisung → Grundlagen → begleitete Maßnahmen → Einsatztraining → FTO-Fahrten → Abschlussprüfung → Streifenfreigabe.','Vier Stufen: Demonstration, Zusammenarbeit, Du führst, Beobachtungsfahrt.'],
16:['Leitstelle und Einsatzplanung','Die Leitstelle nimmt Einsatzmeldungen auf, ordnet sie zu und koordiniert verfügbare Units.','ANM: Auftrag verstehen – nachfragen – Veränderungen und Ergebnisse melden.'],
18:['Vom Fund zur Akte','Beweismittel eindeutig einem Vorgang zuordnen, Übergaben dokumentieren und Laborergebnisse sachlich in die Akte übernehmen.','SÜLA: Sichern – Übergabe dokumentieren – Laborprüfung – Akte ergänzen.'],
21:['Gefahrenlehre','Erkennbare Risiken früh wahrnehmen, Bedeutung beurteilen und angemessene Hilfe organisieren.','E-M-B-H: Erkennen – Melden – Bewerten – Hilfe.']};
const codes=[['10-0','Vorsicht'],['10-3','Sendepause'],['10-4','Verstanden'],['10-7','Außer Dienst'],['10-8','Im Dienst'],['10-9','Bitte wiederholen'],['10-15','Person in Gewahrsam'],['10-20','Standort'],['10-23','Eingetroffen'],['10-41','Dienstbeginn'],['10-42','Dienstende'],['10-50','Verkehrsunfall'],['10-52','EMS anfordern'],['10-76','Auf Anfahrt'],['10-78','Verstärkung'],['10-80','Verfolgungsjagd']];
function dashboard(){title.textContent='Dashboard';content.innerHTML=`<div class="hero"><div class="kicker">FIELD TRAINING OFFICER ABTEILUNG</div><h1>Willkommen zurück, Recruit Carter.</h1><p>Dein zentraler Ausbildungsbereich für Grundlagen, Streifendienst, Dokumentation und persönliche Freigaben.</p></div><div class="grid"><div class="card span3 metric"><small>AUSBILDUNGSFORTSCHRITT</small><strong>37%</strong><div class="progress"><i style="width:37%"></i></div></div><div class="card span3 metric"><small>DIENSTNUMMER</small><strong>#22</strong><span class="badge">AKTIV</span></div><div class="card span3 metric"><small>ZUSTÄNDIGER FTO</small><strong style="font-size:18px">Sgt. Miller</strong><small>Field Training Officer</small></div><div class="card span3 metric"><small>AUSBILDUNGSSTUFE</small><strong>II</strong><span class="badge">ZUSAMMENARBEIT</span></div><div class="card span8"><div class="section-title"><div><h3>Ausbildungsbereiche</h3><small>22 Kapitel aus deinem Rekrutenhandbuch</small></div><small>8 / 22 bearbeitet</small></div><div class="modules">${chapters.slice(0,9).map((c,i)=>`<div class="module" data-open="c${i}"><span class="num ${i<4?'done':''}">${i<4?'✓ ABGESCHLOSSEN':'KAPITEL '+(i+1)}</span><p><b>${c[0]}</b></p><p>${c[1]}</p></div>`).join('')}</div></div><div class="card span4"><div class="section-title"><h3>Nächste Schritte</h3></div><div class="info"><b>Funk & Funkcodes</b><br><span class="label">Wiederholung mit FTO</span></div><div class="info"><b>Verkehrskontrolle</b><br><span class="label">Praktische Ausbildungsfahrt</span></div><div class="info"><b>CAD / Personenabfrage</b><br><span class="label">Noch offen</span></div></div></div>`;bindModules()}
function chapter(i){const c=chapters[i], x=chapterContent[i]||[c[0],c[1],'Die vollständigen Lerninhalte und bebilderten Anleitungen werden hier aus dem Rekrutenhandbuch eingebunden.'];title.textContent=c[0];content.innerHTML=`<div class="chapter-head"><div class="kicker">KAPITEL ${i+1} · REKRUTENAUSBILDUNG</div><h1>${c[0]}</h1><p>${c[1]}</p></div><div class="grid"><div class="card span8 content-card"><h3>${x[0]}</h3><p>${x[1]}</p><div class="info"><b>Merke</b><br>${x[2]}</div>${i===4?`<h3>Funkcodes</h3><div class="code-grid">${codes.map(a=>`<div class="code"><b>${a[0]}</b>${a[1]}</div>`).join('')}</div>`:''}${i===15?checklist():''}</div><div class="card span4"><h3>Ausbildungsstatus</h3><p class="label">Kapitel ${i+1} von 22</p><div class="progress"><i style="width:${Math.round((i+1)/22*100)}%"></i></div><div class="data-row"><span>Status</span><b>${i<4?'Bestanden':'In Ausbildung'}</b></div><div class="data-row"><span>FTO</span><b>Sgt. Miller</b></div><div class="data-row"><span>Nachweis</span><b>${i<4?'03.10.2026':'Offen'}</b></div><div class="info warn"><b>Hinweis</b><br>Die Website dient als Ausbildungsportal und ist nicht mit dem Gameserver oder dem Ingame-CAD verbunden.</div></div></div>`}
function checklist(){return `<h3>Vor der ersten Streife</h3>${['FTO und Ansprechpartner kennengelernt','Department und wichtige Bereiche gezeigt','Recruit-Uniform kontrolliert','Freigaben und Einschränkungen verstanden','Funkkanal und Funkcheck eingerichtet','Laptop-Funktionen vorgeführt','Fahrzeugübernahme und Rufnamen erklärt','Lernziele mit dem FTO vereinbart'].map((x,i)=>`<label style="display:block;padding:9px 0;border-bottom:1px solid #e6edf2"><input type="checkbox" ${i<5?'checked':''}> ${x}</label>`).join('')}`}
function account(){title.textContent='Mein Account';content.innerHTML=`<div class="chapter-head"><div class="kicker">PERSÖNLICHER BEREICH</div><h1>Account & Ausbildungsdaten</h1><p>Diese Daten werden innerhalb des Recruit Portals verwaltet und nicht vom Gameserver übernommen.</p></div><div class="account"><div class="card profile"><div class="big-avatar">TC</div><h3>Tyre Carter</h3><p>Recruit · Alta Police Department</p><span class="badge">ACCOUNT AKTIV</span></div><div class="card"><div class="data-row"><span>Benutzername</span><b>recruit.carter</b></div><div class="data-row"><span>Dienstnummer</span><b>22</b></div><div class="data-row"><span>Rang</span><b>Recruit</b></div><div class="data-row"><span>Zuständiger FTO</span><b>Sgt. Miller</b></div><div class="data-row"><span>Ausbildungsbeginn</span><b>03.10.2026</b></div><div class="data-row"><span>Ausbildungsstufe</span><b>II · Zusammenarbeit</b></div><div class="data-row"><span>Streifenfreigabe</span><b style="color:#b3263d">Noch nicht erteilt</b></div></div></div>`}
function bindModules(){document.querySelectorAll('[data-open]').forEach(e=>e.onclick=()=>go(e.dataset.open))}
function go(p){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='dashboard')dashboard();else if(p==='account')account();else if(p[0]==='c')chapter(+p.slice(1));window.scrollTo(0,0)}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));
document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();document.querySelector('#login').classList.add('hidden');document.querySelector('#app').classList.remove('hidden');go('dashboard')};document.querySelector('#logout').onclick=()=>{document.querySelector('#app').classList.add('hidden');document.querySelector('#login').classList.remove('hidden')};
