-- ALTA PD Recruit Portal V5.3
-- Academy-Termine, Abschlussbewertung und Änderungsverlauf
-- Sicher erneut ausführbar.

create table if not exists public.academy_appointments (
  id uuid primary key default gen_random_uuid(),
  recruit_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  starts_at timestamptz not null,
  location text default '',
  notes text default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_by_name text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.academy_final_evaluations (
  id uuid primary key default gen_random_uuid(),
  recruit_id uuid not null unique references public.profiles(id) on delete cascade,
  strengths text default '',
  improvements text default '',
  recommendation text default '',
  result text not null default 'In Ausbildung',
  author_id uuid references public.profiles(id) on delete set null,
  author_name text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.academy_audit_log (
  id bigint generated by default as identity primary key,
  recruit_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text default 'System',
  action text not null,
  details text default '',
  created_at timestamptz not null default now()
);

alter table public.academy_appointments enable row level security;
alter table public.academy_final_evaluations enable row level security;
alter table public.academy_audit_log enable row level security;

grant select,insert,update,delete on public.academy_appointments to authenticated;
grant select,insert,update,delete on public.academy_final_evaluations to authenticated;
grant select,insert on public.academy_audit_log to authenticated;
grant usage,select on sequence public.academy_audit_log_id_seq to authenticated;

-- Helper: FTO/Admin laut bestehendem profiles.role
create or replace function public.academy_is_staff()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('trainer','admin'));
$$;

-- Policies idempotent neu anlegen
do $$ begin
  drop policy if exists "academy appointments read" on public.academy_appointments;
  drop policy if exists "academy appointments staff write" on public.academy_appointments;
  drop policy if exists "academy evaluations read" on public.academy_final_evaluations;
  drop policy if exists "academy evaluations staff write" on public.academy_final_evaluations;
  drop policy if exists "academy audit read" on public.academy_audit_log;
  drop policy if exists "academy audit insert" on public.academy_audit_log;
end $$;

create policy "academy appointments read" on public.academy_appointments
for select to authenticated using (recruit_id=auth.uid() or public.academy_is_staff());
create policy "academy appointments staff write" on public.academy_appointments
for all to authenticated using (public.academy_is_staff()) with check (public.academy_is_staff());

create policy "academy evaluations read" on public.academy_final_evaluations
for select to authenticated using (recruit_id=auth.uid() or public.academy_is_staff());
create policy "academy evaluations staff write" on public.academy_final_evaluations
for all to authenticated using (public.academy_is_staff()) with check (public.academy_is_staff());

create policy "academy audit read" on public.academy_audit_log
for select to authenticated using (recruit_id=auth.uid() or public.academy_is_staff());
create policy "academy audit insert" on public.academy_audit_log
for insert to authenticated with check (public.academy_is_staff());

-- Automatisches Protokoll fuer wichtige bestehende Academy-Aenderungen.
create or replace function public.academy_write_audit()
returns trigger language plpgsql security definer set search_path=public as $$
declare rid uuid; who text; msg text; act text;
begin
  rid := coalesce(new.recruit_id, old.recruit_id);
  select coalesce(name,'System') into who from public.profiles where id=auth.uid();
  who := coalesce(who,'System');
  if tg_table_name='training_progress' then
    act := case when tg_op='DELETE' then 'Kapitel-Freigabe entfernt' else 'Kapitel-Freigabe geändert' end;
    msg := 'Kapitel '||coalesce(new.chapter,old.chapter)::text;
  elsif tg_table_name='training_goals' then
    act := case when tg_op='DELETE' then 'Ausbildungsziel gelöscht' when tg_op='INSERT' then 'Ausbildungsziel erstellt' else 'Ausbildungsziel geändert' end;
    msg := coalesce(new.goal_text,old.goal_text,'');
  elsif tg_table_name='test_assignments' then
    act := 'Test-Zuweisung geändert'; msg := coalesce(new.test_id,old.test_id,'');
  elsif tg_table_name='field_reports' then
    act := case when tg_op='DELETE' then 'Praxisbericht gelöscht' else 'Praxisbericht gespeichert' end;
    msg := coalesce(new.topics,old.topics,'');
  else return coalesce(new,old); end if;
  insert into public.academy_audit_log(recruit_id,actor_id,actor_name,action,details)
  values(rid,auth.uid(),who,act,msg);
  return coalesce(new,old);
end $$;

do $$ begin
  if to_regclass('public.training_progress') is not null then drop trigger if exists academy_audit_progress on public.training_progress; create trigger academy_audit_progress after insert or update or delete on public.training_progress for each row execute function public.academy_write_audit(); end if;
  if to_regclass('public.training_goals') is not null then drop trigger if exists academy_audit_goals on public.training_goals; create trigger academy_audit_goals after insert or update or delete on public.training_goals for each row execute function public.academy_write_audit(); end if;
  if to_regclass('public.test_assignments') is not null then drop trigger if exists academy_audit_tests on public.test_assignments; create trigger academy_audit_tests after insert or update or delete on public.test_assignments for each row execute function public.academy_write_audit(); end if;
  if to_regclass('public.field_reports') is not null then drop trigger if exists academy_audit_reports on public.field_reports; create trigger academy_audit_reports after insert or update or delete on public.field_reports for each row execute function public.academy_write_audit(); end if;
end $$;
